environment:
    matrix:
    - nodejs_version: "6"

install:
    - ps: Install-Product node $env:nodjs_version
    - npm install

test_script:
    - node --version
    - npm --version
    - npm test

build: off